# Site settings
title: 'Learn by doing!'
description: '...or at least writing about it'
url: 'https://blog.uitlanders.com'
baseurl: 'https://blog.uitlanders.com/'
google_analytics: 'UA-59477598-1'
disqus_shortname: 'uitlanders'
comments: true

author:
 name: 'Tim Preston'
 email: tim.preston at thisdomain.com
 twitter_username: tmpreston
 github_username:  tmpreston
 linkedin_username:  tmpreston

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:categories/:year/:month/:day/:title
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate', 'jekyll-gist']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
